### ISSUE TITLE
org-roam-review requires org-drill

### ISSUE THREAD

**Issue by dmitrym0** [chrisbarrett/nursery#1]
Not sure what the best way to ensure org-drill is installed.

I did:

```
 (use-package org-drill :ensure t)

 (use-package org-roam-review
...
```

**Comment by chrisbarrett** [comment]
Gonna close this one since there was no further discussion or next action, but yes, the way you did it is the way to go--installing the dependcies via package.el, or via your nix overlay, or however you like to install things. :)
