### ISSUE TITLE
Empty list when running org-roam-review 

### ISSUE THREAD

**Issue by dmitrym0** [chrisbarrett/nursery#2]
1. I have a bunch of org-roam entries:

```
➜  org-roam git:(master) ✗ ls -1 *.org|wc -l
     732
```
2. I invoke `org-roam-review`
3. I get "You're up to date"

Expected: Some notes to review.

Is this the expected result?

**Comment by chrisbarrett** [comment]
You need to use `org-roam-review-set-seedling` and friends to apply the SRS properties to your notes before they start showing up in the review list. 

After marking them as seedlings they will have org-drill properties applied, as well as a maturity property, and they should start to appear in the list when they're due for review. You can manipulate the timestamps to confirm they show up, or use `org-roam-review-list-by-maturity` to spot-check they're being categorised correctly.

**Comment by chrisbarrett** [comment]
Feel free to reopen if you need more help here :)
