### ISSUE TITLE
`org-roam-review` error

### ISSUE THREAD

**Issue by Sabicool** [chrisbarrett/nursery#6]
I get the fullowing error when calling the org-roam-review functions (e.g. org-roam-review-bury) on a org-roam file that is due for review:

```
⛔ Warning (org-element): ‘org-element-at-point’ cannot be used in non-Org buffer #<buffer *org-roam-review*> (org-roam-review-mode)
```

**Comment by chrarvi** [comment]
Seems recent org versions made using org-parser (org-roam-node-at-point uses this) in non-org buffers now throw this warning.

Reviewing any file while there is a review buffer will trigger  `org-roam-review--update-review-buffer-entry`, which will compare the node-id to each the entries in the review buffer. That comparison calls `org-roam-node-at-point`.

I could remove the warning by temporarily swapping the major mode to `org-mode` before the call, but I don't think it's the most sensible solution
```diff
diff --git a/lisp/org-roam-review.el b/lisp/org-roam-review.el
index af3a8b6..f1ba640 100644
--- a/lisp/org-roam-review.el
+++ b/lisp/org-roam-review.el
@@ -680,7 +680,8 @@ them as reviewed with `org-roam-review-accept',
     (org-roam-review--with-current-review-buffer
       (let ((continue t)
             (found-pos nil)
-            (id (org-roam-node-id node)))
+            (id (org-roam-node-id node))
+            (major-mode 'org-mode))
         (save-excursion
           (goto-char (point-min))
           (while (and (not found-pos) continue)

```

**Comment by chrisbarrett** [comment]
Thanks for flagging this one @Sabicool, and @christoffer-arvidsson for digging into it--I vaguely remember seeing it in the past when doing a doom upgrade and just shrugging it off!

Feel free to re-open the issue if the change I pushed didn't actually fix the warning.
